version: "3"
services:
  server:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    depends_on:
      - server-db
      - redis
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app

  server-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 127.0.0.1:5432:5432
  
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
